import Footer from "../../component/Footer";
import React from "react";
import type { Metadata } from "next";
import "./globals.css";
   //import localFont from "next/font/local";
  //  import "./globals.css"; const geistSans = localFont({
  //    src: "./fonts/GeistVF.woff",
  //    variable: "--font-geist-sans",
  //    weight: "100 900",
  //  });
  //  const geistMono = localFont({
  //    src: "./fonts/GeistMonoVF.woff",
  //    variable: "--font-geist-mono",
  //   weight: "100 900",
  //  });
 
 export const metadata: Metadata = {
   title: "Create Next App",
  description: "Generated by create next app",
 };
//  import logo  from "./../../public1/logo.png"
//  import Link from "next/link";
 import Navbar from "./../../navbar/navbar";
 export default function RootLayout({
   children,
 }: Readonly<{
   children: React.ReactNode;
 }>) {
  return (
    <html lang="en">
      <body>
     
      
        <div className="bg-slate-950  text-gray-50 h-20 py-5   " >
       
          <div>  
          </div>
       
          <div>  <h1><Navbar/></h1></div>
          
       </div>
        
        
       {children}
       <div><Footer/></div>
      </body>
    </html>
  );
}
        
        
        
        
        
        
        
        
        
        
        
//         {/* <div
//       className="bg-slate-800 h-28 py-1  text-slate-100  ">
      
//       <div> 
//       <h1
//       className=" flex justify-center ">
//        BROQCHAT DURO</h1></div> 
             
//              <div> <ul><li className="flex justify-around py-14"><div className=" hover:text-lime-950"><Link href="/home">about </Link> </div>
//  <div className="hover:text-lime-950">< Link href="/photos">Photos </Link> </div> 
//       <div  className="hover:text-lime-950"><Link href="/contact">contact info </Link> 
//       </div>   </li>
//       </ul>

      
//       </div> */}
//       {/* <div> </div></div> */}
      
       
     
